const courseAdvisorAllCourse = [
  {
    title: "MERN Stack Development",
    thumbnail: "/Assets/Images/courses/courses_1.png",
    authorImg: "/Assets/Images/advisors/Advisor_5.png",
    totalRate: "2350",
    price: "69",
    author: "Alex Jhona",
    rate: "4",
    authorPosition: "Associate Professor",
    tag: "MERN, React",
    lessons: "30",
  },
  {
    title: "React Native",
    thumbnail: "/Assets/Images/courses/courses_2.png",
    authorImg: "/Assets/Images/advisors/Advisor_5.png",
    totalRate: "3520",
    price: "85",
    author: "Alex Jhona",
    rate: "5",
    authorPosition: "Associate Professor",
    tag: "MERN, React",
    lessons: "40",
  },
  {
    title: "PHP Cook With Laravel",
    thumbnail: "/Assets/Images/courses/courses_3.png",
    authorImg: "/Assets/Images/advisors/Advisor_5.png",
    totalRate: "3320",
    price: "75",
    author: "Alex Jhona",
    rate: "5",
    authorPosition: "Associate Professor",
    tag: "PHP, Laravel",
    lessons: "74",
  },
  {
    title: "Core Software",
    thumbnail: "/Assets/Images/courses/courses_4.png",
    authorImg: "/Assets/Images/advisors/Advisor_5.png",
    totalRate: "520",
    price: "79",
    author: "Alex Jhona",
    rate: "4",
    authorPosition: "Associate Professor",
    tag: "Software",
    lessons: "20",
  },
  {
    title: "Science And Arts",
    thumbnail: "/Assets/Images/courses/courses_5.png",
    authorImg: "/Assets/Images/advisors/Advisor_5.png",
    totalRate: "3621",
    price: "64",
    author: "Alex Jhona",
    rate: "5",
    authorPosition: "Associate Professor",
    tag: "OC Division",
    lessons: "63",
  },
  {
    title: "Landskip Yard Service",
    thumbnail: "/Assets/Images/courses/courses_6.png",
    authorImg: "/Assets/Images/advisors/Advisor_5.png",
    totalRate: "452",
    price: "85",
    author: "Alex Jhona",
    rate: "4",
    authorPosition: "Associate Professor",
    tag: "Metal worker",
    lessons: "60",
  },
];

export default courseAdvisorAllCourse;
