const coursesData = [
  {
    title: "MERN Stack Development",
    thumbnail: "/Assets/Images/courses/courses_1.png",
    authorImg: "Assets/Images/profile/profile_1.png",
    totalRate: "2350",
    price: "69",
    author: "Lester V. Ingram",
    rate: "4",
    authorPosition: "Javascript Developer",
    tag: "MERN, React",
    lessons: "30",
  },
  {
    title: "React Native",
    thumbnail: "/Assets/Images/courses/courses_2.png",
    authorImg: "Assets/Images/profile/profile_2.png",
    totalRate: "3520",
    price: "85",
    author: "Harold K. Henderson",
    rate: "5",
    authorPosition: "React Native Developer",
    tag: "MERN, React",
    lessons: "40",
  },
  {
    title: "PHP Cook With Laravel",
    thumbnail: "/Assets/Images/courses/courses_3.png",
    authorImg: "Assets/Images/profile/profile_3.png",
    totalRate: "3320",
    price: "75",
    author: "Eric H. Craig",
    rate: "5",
    authorPosition: "PHP Developer",
    tag: "PHP, Laravel",
    lessons: "74",
  },
  {
    title: "Core Software",
    thumbnail: "/Assets/Images/courses/courses_4.png",
    authorImg: "Assets/Images/profile/profile_4.png",
    totalRate: "520",
    price: "79",
    author: "Elmer J. Santora",
    rate: "4",
    authorPosition: "Software Development",
    tag: "Software",
    lessons: "20",
  },
  {
    title: "Science And Arts",
    thumbnail: "/Assets/Images/courses/courses_5.png",
    authorImg: "Assets/Images/profile/profile_5.png",
    totalRate: "3621",
    price: "64",
    author: "Linda J. Navarro",
    rate: "5",
    authorPosition: "Science And Arts",
    tag: "OC Division",
    lessons: "63",
  },
  {
    title: "Landskip Yard Service",
    thumbnail: "/Assets/Images/courses/courses_6.png",
    authorImg: "Assets/Images/profile/profile_6.png",
    totalRate: "452",
    price: "85",
    author: "Lester V. Ingram",
    rate: "4",
    authorPosition: "Precious stone",
    tag: "Metal worker",
    lessons: "60",
  },
  {
    title: "Computer Science Course",
    thumbnail: "/Assets/Images/courses/courses_7.png",
    authorImg: "Assets/Images/profile/profile_7.png",
    totalRate: "1420",
    price: "69",
    author: "Jasmine A. Tully",
    rate: "5",
    authorPosition: "Software Developer",
    tag: "MERN, React",
    lessons: "39",
  },
  {
    title: "Full Stack Development",
    thumbnail: "/Assets/Images/courses/courses_8.png",
    authorImg: "Assets/Images/profile/profile_8.png",
    totalRate: "3620",
    price: "52",
    author: "Lester V. Ingram",
    rate: "4",
    authorPosition: "Software Developer",
    tag: "MERN, React, PHP",
    lessons: "30",
  },
  {
    title: "Program in Graphic Design",
    thumbnail: "/Assets/Images/courses/courses_9.png",
    authorImg: "Assets/Images/profile/profile_9.png",
    totalRate: "4510",
    price: "88",
    author: "Kim L. Liriano",
    rate: "4",
    authorPosition: "Graphic Design",
    tag: "Design, UI, UX",
    lessons: "50",
  },
];

export default coursesData;
