const eventData = [
  {
    thumbnail: "Assets/Images/events/event_1.png",
    title: "Organizers' Favorite Event",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "7.30 AM - 06.00 PM",
    location: "Arlington, VA, U.S.A.",
    date: "20 Jan 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_2.png",
    title: "Global Cyber Security",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "6.30 AM - 04.00 PM",
    location: "Vancouver, Canada",
    date: "23 Jan 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_3.png",
    title: "Dev Ternity",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "3.30 AM - 04.00 PM",
    location: "Clearwater, FL, U.S.A.",
    date: "26 Jan 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_4.png",
    title: "Unblock CI/CD conference",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "9.20 AM - 05.00 PM",
    location: "Online",
    date: "28 Jan 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_5.png",
    title: "DevOpsCon Munich",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "8.30 AM - 06.00 PM",
    location: "Munich, Germany",
    date: "30 Jan 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_6.png",
    title: "Immerse Global Summit",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "10.30 AM - 06.00 PM",
    location: "Miami, FL, U.S.A.",
    date: "31 Jan 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_7.png",
    title: "ScaleUp 360° Enterprise",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "7.30 AM - 06.00 PM",
    location: "Online",
    date: "2 Feb 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_8.png",
    title: "Haskell eXchange",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "6.30 AM - 06.00 PM",
    location: "London, U.K. & Online",
    date: "5 Feb 2023",
  },
  {
    thumbnail: "Assets/Images/events/event_9.png",
    title: "SREcon Asia/Pacific",
    des: "This is a popular ticketing solution for events ranging from small meetups to large concerts.",
    time: "10.30 AM - 06.00 PM",
    location: "Sydney, Australia",
    date: "10 Feb 2023",
  },
];

export default eventData;
